{% set name = "wagtailnews" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtailnews-{{ version }}.tar.gz
  sha256: 75e5be8743a76eba2d2671e993494d1c36f61258066968acdc595a681607b5fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=5.2.0

test:
  imports:
    - wagtailnews
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/neon-jungle/wagtailnews/
  summary: News / blog plugin for the Wagtail CMS
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
